accounts/urls.py
from django.urls import path,include
from . import views
app_name='accounts'

urlpatterns = [

    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout',views.logout,name='logout'),

]

pages/urls.py
from django.urls import path,include
from . import views
app_name='pages'

urlpatterns = [

    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('category/',views.category,name='category'),
    path('contact/',views.contact,name='contact'),
]

photolab_2/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from accounts.views import userslist
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('accounts/',include('accounts.urls')),
    path('user/',include('user.urls')),
    path('users/',userslist.as_view()),
    path('api/token/',TokenObtainPairView.as_view()),
    path('api/token/refresh/',TokenRefreshView.as_view()),
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views
from user.views import userpics
app_name='user'

urlpatterns = [

    path('dashboard/',views.dashboard,name='dashboard'),
    path('userform/',userpics,name='userpics'),

]

accounts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Userpics(models.Model):
    user = models.CharField(max_length=200,primary_key=True)
    hobby = models.CharField(max_length=20,blank=True)

    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    def __str__(self):
        return self.user

user/forms.py
from django import forms
from .models import Userpics

class userpicsform(forms.ModelForm):
    class Meta():
        model = Userpics
        fields = ['user','photo_main', 'photo_1', 'photo_2', 'photo_3','photo_4','photo_5','photo_6']

accounts/views.py
from django.shortcuts import render,redirect,reverse
from django.contrib import messages,auth
from django.contrib.auth.models import User
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import UsersSerializer

# Create your views here.
def login(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            messages.success(request,'You are logged in!')
            return redirect('pages:index')

    return render(request,'accounts/login.html')


def logout(request):

    auth.logout(request)
    messages.success(request,'Logged out')
    return redirect('pages:index')





def register(request):
    if request.method=='POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username taken ')
                return redirect('accounts:register')

            else:

                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Email taken ')
                    return redirect('accounts:register')
                else:
                    user = User.objects.create_user(username=username,email=email,first_name=first_name,last_name=last_name,password=password)
                    user.save()
                    messages.success(request,'User created!')
                    return redirect('pages:index')



        else:
            messages.error(request,'Passwords do not match')
            return redirect('accounts:register')
    else:

        return render(request, 'accounts/register.html')



class userslist(APIView):

    def get(self,request):
        users = User.objects.all()
        serializer = UsersSerializer(users,many=True)
        return Response(serializer.data)

    def post(self):
        pass

pages/views.py
from django.shortcuts import render
from django.shortcuts import render
from user.models import User
from django.contrib import messages
from django.shortcuts import render,get_object_or_404
from user.models import Userpics
from django.shortcuts import render,redirect

# Create your views here.
def index(request):
    if request.user.is_authenticated and Userpics.objects.filter(user=request.user.username).exists():
        cuser = get_object_or_404(Userpics, user=request.user.username)

        return render(request, 'pages/index.html', {'cuser': cuser})



    else:
        return render(request, 'pages/index.html', )

def category(request):
    return render(request,'pages/category.html')


def contact(request):
    return render(request,'pages/contact.html')

def about(request):

    return render(request,'pages/about.html')

user/views.py
from django.shortcuts import render
from .models import User
from django.contrib import messages
from django.shortcuts import render,get_object_or_404
from .models import Userpics
from django.shortcuts import render,redirect
from .forms import userpicsform


# Create your views here.
def dashboard(request):
    if request.user.is_authenticated:
        cuser = get_object_or_404(Userpics, user=request.user.username)

        return render(request,'dashboard.html',{'cuser':cuser})
    else:
        return render(request, 'dashboard.html',)


def userpics(request):

    if request.method == "POST":
        form = userpicsform(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect("pages:index")
            except:
                pass
        else:
            return render(request, 'accounts/form.html', {'form': form})
    else:
        form = userpicsform()
        return render(request, 'accounts/form.html', {'form': form})

templates/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error: 
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/accounts/form.html
{% extends 'pages/base.html' %}
{% block content %}
{% include '_alerts.html' %}
    {% if user.is_authenticated  %}

    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="inquiryModalLabel">Upload files</h2>
          <button type="button" class="close" data-dismiss="modal">

          </button>
        </div>
        <div class="modal-body">
          <form enctype="multipart/form-data"  method="post" >
            {% csrf_token %}

            {{ form.as_p}}
            <input type="submit" class="btn btn-primary" value="Submit">
          </form>
        </div>
      </div>
    </div>

    {% else %}
    <div class="alert alert-primary" role="alert">
  You need to login in order to upload <a href="{% url 'accounts:register' %}" class="alert-link">Not a user? Register!</a>.
</div>

    {% endif %}

{% endblock %}

templates/accounts/login.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
{% include '_alerts.html' %}
  <section id="login" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-sign-in-alt"></i> Login</h4>
            </div>
            <div class="card-body">

                <form action="#" method="POST">
                  {% csrf_token %}
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>

                <div class="form-group">
                  <label for="password2">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div>

                <input type="submit" value="Login" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/accounts/register.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
{% include '_alerts.html' %}
  <section id="register" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-user-plus"></i> Register</h4>
            </div>
            <div class="card-body">

                <form action="{% url 'accounts:register' %}" method="POST">
                    {% csrf_token %}
                  <div class="form-group">
                  <label for="first_name">First Name</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="last_name">Last Name</label>
                  <input type="text" name="last_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password2">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password">Confirm Password</label>
                  <input type="password" name="password2" class="form-control" required>
                </div>
                <input type="submit" value="Register" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/dashboard.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
{% include '_alerts.html' %}
 <section id="listing" class="py-4">
    <div class="container">



            <div class="section_title mb-33">
                        <h3>Your Uploads</h3>
                    </div>
            <div class="row">
                <div class="col-xl-12"></div></div>

      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img src="{{ cuser.photo_main.url }}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">
              {% if listing.photo_1 %}
                <div class="col-md-2">
                  <a href="{{ cuser.photo_1.url }}" data-lightbox="home-images">
                    <img src="{{ cuser.photo_1.url }}" alt="" class="img-fluid">
                  </a>
                </div>
              {% endif %}
              {% if cuser.photo_2 %}
                <div class="col-md-2">
                  <a href="{{ cuser.photo_2.url }}" data-lightbox="home-images">
                    <img src="{{ cuser.photo_2.url }}" alt="" class="img-fluid">
                  </a>
                </div>
                {% endif %}
              {% if cuser.photo_3 %}
                <div class="col-md-2">
                  <a href="{{ cuser.photo_3.url }}" data-lightbox="home-images">
                    <img src="{{ cuser.photo_3.url }}" alt="" class="img-fluid">
                  </a>
                </div>
                {% endif %}
              {% if cuser.photo_4 %}
                <div class="col-md-2">
                  <a href="{{ cuser.photo_4.url }}" data-lightbox="home-images">
                    <img src="{{ cuser.photo_4.url }}" alt="" class="img-fluid">
                  </a>
                </div>
                {% endif %}
              {% if cuser.photo_5 %}
                <div class="col-md-2">
                  <a href="{{ cuser.photo_5.url }}" data-lightbox="home-images">
                    <img src="{{ cuser.photo_5.url }}" alt="" class="img-fluid">
                  </a>
                </div>
                {% endif %}
              {% if cuser.photo_6 %}
                <div class="col-md-2">
                  <a href="{{ cuser.photo_6.url }}" data-lightbox="home-images">
                    <img src="{{ cuser.photo_6.url}}" alt="" class="img-fluid">
                  </a>
                </div>
                {% endif %}

          </div></div></div></div></section>

{% endblock %}

templates/pages/about.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}



<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

{% include '_alerts.html' %}

    <!-- about_area_start -->
    <div class="about_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="about_text">
                        <h3>Lost Is Just a Four Letter Word</h3>
                        <p class="about_text_1">For man shall him gathering image dry gathering which cattle. Said
                            second fruit dry Upon cattle sixth lights herb gathered second that night sea his blessed he
                            us meat Seed void. Day saw him days itself lights. Give waters multiply earth very brought
                            replenish open itself multiply upon cattle she’d rule make doesn’t lights together I let
                            heaven which for land saw grass our was unto face brought seed dry moving was, were great.
                            Our won’t dry herb set over. Seasons earth upon fill it after. Shall she’d hath so which
                            seas to </p>
                        <p class="about_text_2">
                            For man shall him gathering image dry gathering which cattle. Said second fruit dry Upon
                            cattle sixth lights herb gathered second that night sea his blessed he us meat Seed void.
                            Day saw him days itself lights. Give waters multiply earth very brought replenish open
                            itself multiply upon cattle
                        </p>
                    </div>
                </div>
                <div class="col-xl-12">
                    <div class="about_thumb">
                        <img src="{% static 'img/about/banner.png'%}" alt="">
                    </div>
                </div>
                <div class="about_details">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-6">
                                <p>For man shall him gathering image dry gathering which cattle. Said second fruit dry
                                    Upon cattle sixth lights herb gathered second that night sea his blessed he us meat
                                    Seed void. Day saw him days itself lights.</p>
                            </div>
                            <div class="col-xl-6">
                                <p>For man shall him gathering image dry gathering which cattle. Said second fruit dry
                                    Upon cattle sixth lights herb gathered second that night sea his blessed he us meat
                                    Seed void. Day saw him days itself lights.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- about_area_start -->

    <div class="moderators_area">
        <div class="container">
            <div class="modarator_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <div class="modarator_title">
                        <h3>Our Moderators</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-3 col-md-3">
                    <div class="single_modarators">
                        <div class="moderator_thumb">
                            <img src="{% static 'img/team/1.png'%}" alt="">
                            <div class="author_links">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-envelope"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-linkedin-square"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="moderator_name">
                            <h3>Jack Piller</h3>
                            <p>Photographer at COk</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-3">
                    <div class="single_modarators">
                        <div class="moderator_thumb">
                            <img src="{% static 'img/team/2.png'%}" alt="">
                            <div class="author_links">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-envelope"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-linkedin-square"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="moderator_name">
                            <h3>Macau Wilium</h3>
                            <p>Photographer at COk</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-3">
                    <div class="single_modarators">
                        <div class="moderator_thumb">
                            <img src="{% static 'img/team/3.png'%}" alt="">
                            <div class="author_links">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-envelope"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-linkedin-square"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="moderator_name">
                            <h3>Ander Doe</h3>
                            <p>Photographer at COk</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-3">
                    <div class="single_modarators">
                        <div class="moderator_thumb">
                            <img src="{% static 'img/team/4.png'%}" alt="">
                            <div class="author_links">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-envelope"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-linkedin-square"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="moderator_name">
                            <h3>Clurk Amila</h3>
                            <p>Photographer at COk</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- subscribe_newsletter_start -->
    <div class="subscribe_newsletter">
        <div class="container">
            <div class="black_bg">
                <div class="row">
                    <div class="col-xl-6">
                        <div class="newsletter_text">
                            <h3>
                                Subscribe newsletter
                            </h3>
                            <p>Get updates to our newsletter and new articles</p>
                        </div>
                    </div>
                    <div class="col-xl-6">
                        <div class="newsform">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- subscribe_newsletter_end -->

    <!-- instagram_media_area_start -->
    <div class="instagram_media_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="instagram_title text-center">
                        <i class="fa fa-instagram"></i>
                        <h3>@photomedia</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-3 col-md-3">
                    <div class="single_instragram">
                        <img src="{% static 'img/instagram/1.png'%}" alt="">
                    </div>
                </div>
                <div class="col-xl-3 col-md-3">
                    <div class="single_instragram">
                        <img src="{% static 'img/instagram/2.png'%}" alt="">
                    </div>
                </div>
                <div class="col-xl-3 col-md-3">
                    <div class="single_instragram">
                        <img src="{% static 'img/instagram/3.png'%}" alt="">
                    </div>
                </div>
                <div class="col-xl-3 col-md-3">
                    <div class="single_instragram">
                        <img src="{% static 'img/instagram/4.png'%}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- instagram_media_area_end -->
{% endblock %}
</body>

</html>

templates/partials/footer.html
{% load static %}
<!-- footer_start -->
    <footer class="footer">
        <div class="footer_area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="footer_info text-center">
                            <div class="footer_logo text-center">
                                <a href="#">
                                    <img src="{% static 'img/footer-logo.png'%}" alt="">
                                </a>
                            </div>
                            <p class="footer_text">
                                Explore photo media blog to enrich your photography knowledge
                            </p>
                            <div class="header_links">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                                    <li><a class="twiter" href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a class="insta" href="#"> <i class="fa fa-instagram"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer_bottom ">
            <div class="container">
                <div class="footer_border">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="footer_links text-center">
                                <ul>
                                    <li><a href="{% url 'pages:index' %}">home</a></li>
                                    <li><a href="{% url 'pages:category' %}">category</a></li>
                                    <li><a href="{% url 'pages:about' %}">about</a></li>
                                    <li><a href="{% url 'pages:contact' %}">contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright_text text-center">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </p>
            </div>
        </div>
    </footer>
    <!-- footer_end -->

templates/partials/header.html
{% load static %}
    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div class="header_top">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-4 col-md-4 d-none d-md-block">
                            <div class="header_links ">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                                    <li><a class="twiter" href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a class="insta" href="#"> <i class="fa fa-instagram"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-4 col-md-4">
                            <div class="logo">
                                <a href="{% url 'pages:index' %}">
                                    <img src="{% static 'img/logo.png'%}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-4 col-md-4 d-none d-md-block">
                            <div class="login_resiter">
                                {% if user.is_authenticated %}
                                 <p><a href="{% url 'accounts:logout' %}"><i class="flaticon-user"></i>logout</a>| <a href="{% url 'user:dashboard' %}">{{ user.username }}(dashboard)</a>|<br> <a href="{% url 'user:userpics' %}">Upload Pictures</a></p>
                                {% else %}
                                <p><a href="{% url 'accounts:login' %}"><i class="flaticon-user"></i>login</a> | <a href="{% url 'accounts:register' %}">Register</a></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="sticky-header" class="main-header-area white-bg">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-7 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="{% url 'pages:index' %}">Home</a></li>
                                        <li><a href="{% url 'pages:category' %}">catagory</a></li>
                                        <li><a href="{% url 'pages:about' %}">About</a></li>


                                        <li><a href="{% url 'pages:contact' %}">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-5">
                            <div class="get_serch">
                                <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                    <div class="search_input" id="search_input_box">
                            <div class="container ">
                                <form class="d-flex justify-content-between search-inner">
                                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                                    <button type="submit" class="btn"></button>
                                    <span class="ti-close" id="close_search" title="Close Search"></span>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->